### ISSUE TITLE
Does this plugin work with binary ninja v3?

### ISSUE THREAD

**Issue by StillFantastic** [crytic/ethersplay#54]
I followed the installation instructions, but nothing changed after I pasted contract runtime bytecode in raw hex.

**Comment by ekilmer** [comment]
@StillFantastic Does it work now? What was your solution?

**Comment by StillFantastic** [comment]
@ekilmer Yeah, I'm pretty new to binary ninja, so I didn't notice the default python interpreter was a wrong one. After I generate the graph there are still many unimplemented instruction errors though.

**Comment by ekilmer** [comment]
Got it! Just wanted to make sure.

The unimplemented instructions are certainly worth reporting in a new issue if you can give some good information regarding how to reproduce the errors you see. I'm not all that familiar with the project tbh, but it looks like here is where the supported instructions are listed https://github.com/crytic/ethersplay/blob/d3186f57f39b07a9ebcfc34da01a18b42973dff3/ethersplay/evm.py#L164-L259

**Comment by StillFantastic** [comment]
@ekilmer Thank you, that's really helpful! I'll see what I can do and hopefully send a PR.
