### ISSUE TITLE
add to the plugin manager?

### ISSUE THREAD

**Issue by psifertex** [crytic/ethersplay#57]
If ya'll are interested, it wouldn't take much to add ethersplay to the [plugin manager](https://github.com/vector35/community-plugins) which would be nice for discoverability. In short, [update the plugin.json](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#2-create-your-pluginjson), and create the appropriately versioned [release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release). 

(You might find https://github.com/vector35/release_helper helpful, as incrementing the version number in the plugin and creating the tag/release can be mildly tedious otherwise). 

Other than that, just let me know when the changes are done and I'll add it to the plugin manager. We'll automatically keep it updated to track the releases, no future notification necessary.

**Comment by ekilmer** [comment]
Hey @psifertex I took a stab at updating the `plugin.json` in #58. However, I'm getting some unimplemented instruction (LLIL) warnings/errors on the example `test.evm` file (testing with Binja `3233`).

I don't know when I'll get time to look into this, but it would be nice to have those warnings fixed before making a release.

**Comment by psifertex** [comment]
That's several stable versions old with of BN -- the latest stable doesn't have those:

<img width="1624" alt="Screenshot 2022-11-02 at 4 35 14 PM" src="https://user-images.githubusercontent.com/140215/199597218-50d3bc5f-671d-40b1-8d88-c9c9f031e353.png">

Unless you mean the tags on the left gutter? Those are legitimate issues where the architecture plugin doesn't lift instructions and it's important to highlight them so the user knows what is and isn't implemented. Those aren't controllable by a plugin as far as I know but users can easily disable them if they don't want to see them by unchecking them in the "tag types" tab section of the "tags" left pane.

**Comment by ekilmer** [comment]
Just tested again on the latest stable release, and indeed, the errors have disappeared. I'll update the minimum binary ninja version to current stable.

> Unless you mean the tags on the left gutter? Those are legitimate issues where the architecture plugin doesn't lift instructions and it's important to highlight them so the user knows what is and isn't implemented. Those aren't controllable by a plugin as far as I know but users can easily disable them if they don't want to see them by unchecking them in the "tag types" tab section of the "tags" left pane.

Ah! Thank you for the explanation.

**Comment by ekilmer** [comment]
@psifertex I tagged a release! https://github.com/crytic/ethersplay/releases/tag/v0.1.0

Please add it to the plugin manager 😄. Thank you for the help!

**Comment by psifertex** [comment]
Great! Added! From now on, any time you trigger a new release we should see it and will update the version in the plugin manager without any other interaction from ya'll. :-)
